---
version: '3.7'

services:
  lke-server:
    networks:
      - lke_network
      - traefik_network
    labels:
      - "traefik.docker.network=traefik_network"
      - "traefik.enable=true"
      - "traefik.http.routers.lke-server-secure.entrypoints=https"
      - "traefik.http.routers.lke-server-secure.rule=Host(`lke.${TRAEFIK_HOST}`)"

networks:
  lke_network:
  traefik_network:
    external: true
