---
version: '3.9'

services:
  elastic:
    # fixed to 7.10.2 due to elastic licencing
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-7.10.2}
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m  -Dlog4j2.formatMsgNoLookups=true -Dlog4j2.disable.jmx=true'
    ulimits:
      memlock:
        # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_disable_swapping
        soft: -1
        hard: -1
    ports:
      - "9200:9200-9299"
    networks:
      - lke_network

networks:
  lke_network:
