---
version: '3.7'

services:
  lke-server:
    image: ${REPOSITORY}linkurious/lke-server:${LKE_SERVER_VERSION}
    init: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: ".env.lke-server.${RUN_ENV}"
    networks:
      - lke_network
    volumes:
      - lke_data:/data

  lke-frontend:
    image: ${REPOSITORY}linkurious/lke-frontend:${LKE_FRONTEND_VERSION}
    init: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - lke_network


volumes:
  lke_data:

networks:
  lke_network:
