{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkurious-enterprise.fullname" . }}-litestream
  labels:
    {{- include "linkurious-enterprise.labels" . | nindent 4 }}
data:
  litestream.yaml: |+
    ---
    # https://litestream.io/reference/config/
    dbs:
      - path: /data/server/database.sqlite
        replicas:
          - endpoint:  https://s3.fr-par.scw.cloud
            type: s3
            region: fr-par
            bucket: lk-{{ .Release.Namespace }}-backup-lke
            force-path-style: true
            path: backup/{{ include "linkurious-enterprise.fullname" . }}
            retention: 720h # 24h * 30
            snapshot-interval: 24h

{{- end }}
