{{- if .Values.backup.litestream.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkurious-enterprise.fullname" . }}-litestream
  labels:
    {{- include "linkurious-enterprise.labels" . | nindent 4 }}
data:
  litestream.yaml: |+
    ---
    # https://litestream.io/reference/config/
    dbs:
      - path: /data/server/database.sqlite
        replicas:
          - endpoint: {{ .Values.backup.litestream.config.url }}
            type: {{ .Values.backup.litestream.config.type }}
            region: {{ .Values.backup.litestream.config.region }}
            bucket: {{ tpl .Values.backup.litestream.config.bucket . }}
            force-path-style: true
            path: backup/{{ include "linkurious-enterprise.fullname" . }}
            retention: 720h # 24h * 30
            snapshot-interval: 24h

{{- end }}
