{{- if .Values.configEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkurious-enterprise.fullname" . }}-configmap
  labels:
    {{- include "linkurious-enterprise.labels" . | nindent 4 }}
  {{- if .Values.configAnnotations }}
  annotations:
  {{- range $key, $value := .Values.configAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
  docker.json: |-
    {{- include "linkurious-enterprise.config" $  | fromYaml | mustToPrettyJson |  nindent 4}}
{{- end }}
