{{- if or (.Values.configEnabled) (.Values.configOverlayEnabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkurious-enterprise.fullname" . }}-configmap
  labels:
    {{- include "linkurious-enterprise.labels" . | nindent 4 }}
  {{- if .Values.configAnnotations }}
  annotations:
  {{- range $key, $value := .Values.configAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data:
{{- if .Values.configOverlayEnabled }}
  overlay.json: |-
{{- else }}
  docker.json: |-
{{- end }}
  {{- $configData := include "linkurious-enterprise.config" $| fromYaml }}
  {{- if semverCompare ">=4.2.0" (.Values.image.tag | default .Chart.AppVersion) }}
  {{- $clusterConfig := dict "enabled" (gt (int .Values.replicaCount) 1) "mode" "$ENV:LKE_CLUSTER_ROLE" }}
  {{- $configData = dict "cluster" $clusterConfig }}
  {{- $configData = mergeOverwrite $configData (include "linkurious-enterprise.config" $| fromYaml) }}
  {{- end }}
  {{- $configData | mustToPrettyJson |  nindent 4 }}
{{- end }}
