apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkurious-enterprise.fullname" . }}
  labels:
    {{- include "linkurious-enterprise.labels" . | nindent 4 }}
  annotations:
    {{- if gt (int .Values.replicaCount) 1 }}
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: lke-sticky-cookie
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: "strict"
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.metrics.prometheus }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    {{- end }}
  selector:
    {{- include "linkurious-enterprise.selectorLabels" . | nindent 4 }}
