{{- if .Values.backup.velero.primaryBackup.enabled }}
{{- if (not (.Capabilities.APIVersions.Has "velero.io/v1")) }}
    {{- fail "ERROR: You have to deploy velero.io/v1 first or disable velero backup" }}
{{- end }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ printf "velero-schedule-%s" $.Release.Namespace }}
  namespace: {{ .Values.backup.velero.veleroNamespace }}
  {{- if .Values.backup.velero.annotations }}
  annotations:
    {{- toYaml .Values.backup.velero.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- $defaultLabels := dict "app.kubernetes.io/name" .Values.backup.velero.name "app.kubernetes.io/instance" .Values.backup.velero.instance "app.kubernetes.io/managed-by" $.Release.Service }}
    {{- toYaml (mergeOverwrite $defaultLabels (.Values.backup.velero.labels | default dict)) | nindent 4 }}

spec:
{{- if .Values.backup.velero.paused }}
  paused: {{ .Values.backup.velero.paused }}
{{- end }}
{{- if .Values.backup.velero.useOwnerReferencesInBackup }}
  useOwnerReferencesInBackup: {{ .Values.backup.velero.useOwnerReferencesInBackup }}
{{- end }}
  schedule: {{ .Values.backup.velero.primaryBackup.schedule }}
  skipImmediately: {{ .Values.backup.velero.skipImmediately }}
  template:
    defaultVolumesToFsBackup: {{ .Values.backup.velero.primaryBackup.defaultVolumesToFsBackup }}
    includedNamespaces:
       - {{ $.Release.Namespace }}
{{- if .Values.backup.velero.includedResources }}
    includedResources:
    {{- range .Values.backup.velero.includedResources }}
      - {{ . }}
    {{- end }}
{{- end }}
{{- if .Values.backup.velero.excludedResources }}
    excludedResources:
    {{- range .Values.backup.velero.excludedResources }}
      - {{ . }}
    {{- end }}
{{- end }}
{{- if .Values.backup.velero.labelsSelector }}
    labelSelector:
      matchLabels:
        {{- toYaml .Values.backup.velero.labelsSelector | nindent 8 }}
{{- end }}
{{- if .Values.backup.velero.primaryBackup.snapshotMoveData }}
    snapshotMoveData: {{ .Values.backup.velero.primaryBackup.snapshotMoveData }}
{{- end }}
    snapshotVolumes: {{ .Values.backup.velero.primaryBackup.snapshotVolume }}
{{- if .Values.backup.velero.primaryBackup.storageLocation }}
    storageLocation: {{ .Values.backup.velero.primaryBackup.storageLocation }}
{{- end }}
    ttl: {{ .Values.backup.velero.primaryBackup.ttl }}
{{- end }}
