{{- if .Values.backup.velero.secondaryBackup.enabled }}
{{- if (not (.Capabilities.APIVersions.Has "velero.io/v1")) }}
    {{- fail "ERROR: You have to deploy velero.io/v1 first or disable velero backup" }}
{{- end }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ printf "velero-secondary-schedule-%s" $.Release.Namespace }}
  namespace: {{ .Values.backup.velero.veleroNamespace }}
  {{- if .Values.backup.velero.annotations }}
  annotations:
    {{- toYaml .Values.backup.velero.annotations | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.backup.velero.name }}
    app.kubernetes.io/instance: {{ .Values.backup.velero.instance }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
   {{- if .Values.backup.velero.labels }}
      {{- toYaml .Values.backup.velero.labels | nindent 4 }}
    {{- end }}

spec:
{{- if .Values.backup.velero.paused }}
  paused: {{ .Values.backup.velero.paused }}
{{- end }}
{{- if .Values.backup.velero.useOwnerReferencesInBackup }}
  useOwnerReferencesInBackup: {{ .Values.backup.velero.useOwnerReferencesInBackup }}
{{- end }}
  schedule: {{ .Values.backup.velero.secondaryBackup.schedule }}
  skipImmediately: {{ .Values.backup.velero.skipImmediately }}
  template:
    defaultVolumesToFsBackup: {{ .Values.backup.velero.secondaryBackup.defaultVolumesToFsBackup }}
    includedNamespaces:
       - {{ $.Release.Namespace }}
{{- if .Values.backup.velero.includedResources }}
    includedResources:
    {{- range .Values.backup.velero.includedResources }}
      - {{ . }}
    {{- end }}
{{- end }}
{{- if .Values.backup.velero.excludedResources }}
    excludedResources:
    {{- range .Values.backup.velero.excludedResources }}
      - {{ . }}
    {{- end }}
{{- end }}
{{- if .Values.backup.velero.labelsSelector }}
    labelSelector:
      matchLabels:
        {{- toYaml .Values.backup.velero.labelsSelector | nindent 8 }}
{{- end }}
{{- if .Values.backup.velero.secondaryBackup.snapshotMoveData }}
    snapshotMoveData: {{ .Values.backup.velero.secondaryBackup.snapshotMoveData }}
{{- end }}
    snapshotVolumes: {{ .Values.backup.velero.secondaryBackup.snapshotVolume }}
{{- if .Values.backup.velero.secondaryBackup.storageLocation }}
    storageLocation: {{ .Values.backup.velero.secondaryBackup.storageLocation }}
{{- end }}
    ttl: {{ .Values.backup.velero.secondaryBackup.ttl }}
{{- end }}
