image:
  repository: hub.docker.nexus3.linkurious.net/linkurious/linkurious-enterprise
  tag: 4.1.8

configOverlayEnabled: false
metrics:
  prometheus:
    enabled: false

persistentVolume:
  enabled: true
  ## Linkurious Enterprise data Persistent Volume Storage Class
  ## If defined here, sets storageClassName: <storageClass> in the generated PersistentVolumeClaim
  ## If set to "-" here, sets storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, then, no storageClassName spec is
  ##   set, thus choosing the default provisioner.
  ## Possible values:
  ## * "managed-csi-premium" provisions premium SSD disks (recommended)
  ## * "managed-csi" provisions standard SSD-backed disks
  ## Do not use azurefile-based storage classes, they are not compatible.
  storageClass: "managed-csi-premium"
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  annotations: {}
